Repository g12-4soat/techlanches-lambda-auth, pull requests merged in 2024-03, with the labels that each got.

#8 Feature/lambda terraform
  src/Serverless/auth_lambda.zip
  src/terraform/modules/apiGateway/main.tf
  src/terraform/modules/apiGateway/vars.tf
  src/terraform/provider.tf
  src/terraform/secrets-manager.tf
  src/terraform/variables.tf
Labels: bug, enhancement

#10 Feature/gateway eks
  src/terraform/main.tf
  src/terraform/modules/apiGateway/main.tf
  src/terraform/modules/apiGateway/output.tf
  src/terraform/modules/apiGateway/vars.tf
Labels: enhancement

#12 correção da sequencia de criação para pipeline
  src/terraform/modules/apiGateway/main.tf
Labels: bug
